language: python

python: 2.7

sudo: false

cache:
  directories:
  - eggs
  - parts/node

install:
- python bootstrap.py
- bin/buildout annotate
- bin/buildout

script:
- bin/code-analysis
- bin/test

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v

after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
