language: python

python: 2.7

sudo: false

install:
- sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg -N -q

cache:
  directories:
  - eggs
  - parts/node

install:
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v

script:
- bin/code-analysis
- bin/test

after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
