language: python

python: 2.7

sudo: false

cache:
  directories:
  - eggs
  - parts/node

install:
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout
  - flake8 --max-complexity=10 --select=C distarray

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v

script:
- bin/code-analysis
- bin/test

after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
